### ISSUE TITLE
Feature Request: allow manual setting of fonts

### ISSUE THREAD

**Issue by brimwats** [kepano/obsidian-advanced-appearance#1]
I generally like to use a different font alltogether for obsidian (fira code or operator mono). Request for allowing the setting of fonts manually. 

 California Coast theme does it this way:

![image](https://user-images.githubusercontent.com/49103046/104084277-93e71180-51fa-11eb-96e8-e6ca53328c56.png)

Perhaps this could be under an "advanced customization" tab?

**Comment by kepano** [comment]
This is already available if you scroll down to the bottom of the settings. In fact I believe California Coast uses my code from Minimal plugin :)
