### ISSUE TITLE
Readable line length

### ISSUE THREAD

**Issue by Fastidious** [kepano/obsidian-advanced-appearance#11]
The plugin is interfering with the r**eadable line length** (which I have turned off on the editor options). Is there a way to disable that? Setting **line width** to blank, or to a big number (1200, 1500) gets closer, but there is still too much margin each side.

**Comment by kepano** [comment]
This setting is not yet available in the UI but you can define margins using a CSS snippet. Here's the default:

```
:root {
  --max-width:87%;
}
```

**Comment by Fastidious** [comment]
No, that’s not it. 

With the default theme, or any other theme, I can make Obsidian window the whole size of my screen (not full screen), and text will flow to the size of the content space, with a relatively small margin each side. With this plugin, even as I have **readable line length** turned off, ** line width** to 1500, and playing with all percentages of the snipped you recommended, the content remains with a margin a few times bigger. See below.

Plugin is inactive:

<img width="2629" alt="Screenshot 2021-02-12 at 15 42 32" src="https://user-images.githubusercontent.com/8352292/107820620-19edff00-6d49-11eb-817d-7524d19f11e4.png">

Plugin is active:

<img width="2629" alt="Screenshot 2021-02-12 at 15 43 18" src="https://user-images.githubusercontent.com/8352292/107820652-24a89400-6d49-11eb-97cd-87825e80bab7.png">

**Comment by kepano** [comment]
I am 99% certain that the setting above is the one you want to play with. You may need to add the `!important` flag. I'll look into adding this as a setting in the UI at some point.

**Comment by Fastidious** [comment]
Instead of adding the setting, why not to abide by the setting in Obsidian itself? If Obsidian is set with the readable line length off, then it is meant to be off. Margins shouldn’t be tampered with either. Better approach?

**Comment by kepano** [comment]
I'm going to make a small tweak which should address your needs assuming you are using the default theme. AFAIK plugins don't have access to the Obsidian settings so I have to rely on the CSS classes that get injected, but those are narrowly scoped which is a limitation for themes like Minimal where the margin settings are also used to align the title bar.
