### ISSUE TITLE
Readable Line length doesnt work

### ISSUE THREAD

**Issue by lenicyl** [kepano/obsidian-advanced-appearance#19]
HeyI just wanted to know how i can remove the huge Margin. Im fairly new and didnt find anything in the settings
Later i realised that readable line length doesnt work with Advanced Appearance. How do you get readable line length in Advanced appearance ? 
Any CSS snippets would also be fine with me 

![image](https://user-images.githubusercontent.com/73347143/120757556-52029300-c52e-11eb-85c9-d812b57f7ded.png)

**Comment by kepano** [comment]
There is a "line width" setting under Typography in Advanced Appearance

**Comment by lenicyl** [comment]
> There is a "line width" setting under Typography in Advanced Appearance

Okay ill check it out
Thanks for the help
