### ISSUE TITLE
Bug: "base color darkness" slider does nothing

### ISSUE THREAD

**Issue by julianstoerig** [kepano/obsidian-advanced-appearance#5]
I installed the plugin (version 1.0.2) via obsidian (v0.10.6), and for some reason, the "base color darkness" slider seems to not do anything.
![image](https://user-images.githubusercontent.com/55281225/104107443-7a0e0300-52bc-11eb-8de9-2b4716c34f46.png)

![image](https://user-images.githubusercontent.com/55281225/104107448-86925b80-52bc-11eb-8e4c-281024140dd4.png)

**Comment by kepano** [comment]
It looks like you’re in dark mode. This slider only affects light mode for now.

**Comment by julianstoerig** [comment]
oh that explains a lot, thx
