### ISSUE TITLE
Bug: UI Black When Using Light Mode

### ISSUE THREAD

**Issue by YE17** [kepano/obsidian-advanced-appearance#6]
When the base theme is set to light, the UI is just black and hard to read.

![Obsidian_UeMUn4aJeE](https://user-images.githubusercontent.com/39507149/104109245-cc313300-5280-11eb-9af5-91e0b6816c7c.png)

**Comment by kepano** [comment]
@YE17 what theme are you using?

**Comment by YE17** [comment]
I'm not using any theme, just the regular Obsidian theme. No snippets either.

**Comment by kepano** [comment]
Thanks for catching this. It is fixed in 1.0.3. The issue was that the default base lightness was not being set correctly.
