### ISSUE TITLE
Bug: Darkmode Illegible For Default Theme

### ISSUE THREAD

**Issue by YE17** [kepano/obsidian-advanced-appearance#9]
Hmm... Light mode works well for both Default and Minimal, but... Darkmode with the default theme now looks entirely dark and the settings menu is completely transparent:
![Obsidian_xDFlkAInDN](https://user-images.githubusercontent.com/39507149/104772525-6d5c3580-5728-11eb-8b84-1221f06c5260.png)

**Comment by kepano** [comment]
This is fixed in 1.0.6 — thanks!
